version: 2.1

# enable CircleCI dynamic configuration
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: detect-secrets
          mapping: |
            detect-secrets/.* detect-secrets true
          base-revision: main
          config-path: detect-secrets/continue_config.yml
