#!/usr/bin/env bash
set -euo pipefail

# Usage:
# ./build
# or
# ./build 1.2.0-1
# or
# ./build 20230101.1
# or
# ./build latest
# or
# ./build ci

ALLOWED_ARGS="[0-9]+\.[0-9]+\.[0-9]+\-[0-9]+|^[0-9]{8}.[0-9]{1,}$|latest|ci"

TAG=

# If more than one argument is passed, exit
if [[ $# -gt 1 ]]; then
  echo "Usage: ./build"
  echo "or"
  echo "Usage: ./build [version]"
  exit 1
fi

# If an argument is passed, set the TAG to the argument
if [[ $# -eq 1 ]]; then
  # If the argument is not of the allowed format, exit
  if [[ ! $1 =~ $ALLOWED_ARGS ]]; then
    echo "Invalid argument: $1"
    echo "Allowed argument format(s): 1.2.3-1, 20230101.1, latest, ci"
    exit 1
  fi
  TAG=$1
fi

# If no arguments are passed, set the TAG to: current-date.seconds (20230101.123)
if [[ $# -eq 0 ]]; then
  TAG=$(date +%Y%m%d).$(date +%s)
fi

docker build -t artsy/detect-secrets:$TAG .
