#!/usr/bin/env bash
set -euo pipefail

# Usage:
# ./push 1.2.0-1
# or
# ./push latest

TAG=

# if argument is passed, set the TAG to the argument
if [[ $# -eq 1 ]]; then
  TAG=$1
else
  echo "Usage: ./push [version]"
  exit 1
fi

docker push artsy/detect-secrets:$TAG
